### ISSUE TITLE
User Registration/Login

### ISSUE THREAD

**Issue by nafisaakter** [Project-PetCare/petcare-app#1]
## Description

This feature will allow users to create new accounts using their email and password, as well as sign in using existing credentials or alternative methods such as Google authentication.

## Features
- [X] #23
- [X] Sign up with email and password
- [X] Sign in with email and password
- [x] #48
- [x] #22 
- [x] #21

**Comment by t2haev00** [comment]
> w: file:///home/runner/work/petcare-app/petcare-app/app/src/main/java/fi/project/petcare/viewmodel/AuthViewModel.kt:124:35 'modifyUser(Boolean = ..., String? = ..., UserUpdateBuilder.() -> Unit): UserInfo' is deprecated. Use updateUser instead

Does this has signifigance?
