### ISSUE TITLE
Improve visual appeal with background images, colors or animations

### ISSUE THREAD

**Issue by yeroldsan** [Project-PetCare/petcare-app#47]
**Is your feature request related to a problem? Please describe.**
Currently, our application lacks visual appeal and might feel a bit bland. Users might find it less engaging or memorable compared to other visually appealing applications.

**Describe the solution you'd like**
Adding background images, colors, or animations to some elements of the application. This would enhance the visual appeal and create a more immersive user experience.

**Describe alternatives you've considered**
Right now we're focusing solely on functionality and not prioritizing visual enhancements in several screens. However, this approach may result in a less engaging user experience.

**Comment by Hamza919p** [comment]
@yeroldsan  please provide key, url and serverClientId. I am going to work on this issue

**Comment by t2haev00** [comment]
> @yeroldsan please provide key, url and serverClientId. I am going to work on this issue

Hi,

Thank you for your interest, however this application is part of our University course as a graded assignment, henceforth we are not allowed to receive help from other people. 😊
